export const TYPE_SEARCH_PRODUCT_REQUEST = '@product/SEARCH_PRODUCT_REQUEST';
export const TYPE_SEARCH_PRODUCT_SUCCESS = '@product/SEARCH_PRODUCT_SUCCESS';
export const TYPE_SEARCH_PRODUCT_FAILURE = '@product/SEARCH_PRODUCT_FAILURE';

export const TYPE_PRODUCT_DETAILS_REQUEST = '@product/PRODUCT_DETAILS_REQUEST';
export const TYPE_PRODUCT_DETAILS_SUCCESS = '@product/PRODUCT_DETAILS_SUCCESS';
export const TYPE_PRODUCT_DETAILS_FAILURE = '@product/PRODUCT_DETAILS_FAILURE';

export const TYPE_SET_LOADING = '@product/SET_LOADING';